actor 管理ユーザー権限 as admin
actor 趣味マッチングアプリ as system

admin -- (趣味を登録する)
(趣味を登録する) -- system

admin -- (趣味カテゴリを登録する)
(趣味カテゴリを登録する) -- system

admin -- (回答をユーザーにリクエストする)
(回答をユーザーにリクエストする) -- system

(回答をユーザーにリクエストする) ..> (新しいカテゴリや趣味が増えた時などに一斉に実施する)  : <<extend>>
(回答をユーザーにリクエストする) ..> (新規ユーザーや前回回答から一定期間が経った場合など)  : <<extend>>

admin -- (集計結果をユーザーに告知する)
(集計結果をユーザーに告知する) -- system

(集計結果をユーザーに告知する) ..> (一定基準以上集計または期限を超えたとき)  : <<extend>>
