actor 一般ユーザー権限 as nomal
actor 趣味マッチングアプリ as system

nomal -- (どの趣味が好きか回答する)
(どの趣味が好きか回答する) -- system

nomal -- (回答状況・集計をみる)
(回答状況・集計をみる) -- system

(回答状況・集計をみる) ..> (部署ごとの統計)  : <<extend>>
(回答状況・集計をみる) ..> (回答したユーザーを知る)  : <<extend>>
